# Generated by Django 5.1.5 on 2025-01-21 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antrenor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=30)),
                ('soyadi', models.CharField(max_length=30)),
                ('unvan', models.TextField(choices=[('BANT', 'Baş Antrenor'), ('ANT', 'Antrenor'), ('DYT', 'Diyetisyen'), ('PSK', 'Psikolog')], default='ANT')),
                ('resim', models.ImageField(upload_to='media/')),
                ('ozet', models.TextField()),
                ('ozgecmis', models.TextField()),
                ('telefon', models.CharField(max_length=10)),
                ('instagram', models.CharField(max_length=50)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
                ('dogum_yili', models.IntegerField()),
                ('boy', models.IntegerField()),
                ('kilo', models.IntegerField()),
                ('ayak', models.IntegerField()),
                ('veli', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası formatı: '+530 555 5555'", regex='^5.*$')])),
                ('kaynak', models.TextField(choices=[('INS', 'Instagram'), ('INT', 'Internet'), ('TAV', 'Tavsiye'), ('DGR', 'Diğer')])),
                ('ders_suresi', models.TextField(choices=[('0', 'Hiç Ders Almadı'), ('1', 'Bir yıla kadar'), ('3', 'Bir yıl üç yıl'), ('4', 'Üç yıldan fazla')])),
                ('beklenti', models.TextField(choices=[('OGR', 'Yüzmeyi Öğrenmek'), ('TEK', 'Stilli Yüzmek'), ('INT', 'Spor Yapmak'), ('TAV', 'Profosyonel Sporcu Olmak'), ('DGR', 'Diğer')])),
                ('ders_turu', models.TextField(choices=[('OZL', 'Özel Ders'), ('GRP', 'Grup Dersi'), ('TKM', 'Takım')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.CharField(max_length=50)),
                ('ozet', models.TextField()),
                ('aciklama', models.TextField()),
                ('resim', models.ImageField(blank=True, null=True, upload_to='')),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(default='Fk Alpha Academy', max_length=100)),
                ('link', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.TextField(choices=[('BLOG', 'Blog'), ('DUYURU', 'Duyuru')], default='BLOG')),
                ('baslik', models.CharField(max_length=100)),
                ('metin', models.TextField()),
                ('resim', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.antrenor')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
