# Generated by Django 5.1.7 on 2025-03-25 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sporcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=30)),
                ('soyadi', models.CharField(max_length=30)),
                ('anne', models.CharField(max_length=30)),
                ('baba', models.CharField(max_length=30)),
                ('cinsiyet', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=30)),
                ('dogum_tarihi', models.DateField()),
                ('okulu', models.CharField(max_length=30)),
                ('resim', models.ImageField(upload_to='media/')),
                ('telefon', models.CharField(max_length=10)),
                ('telefon_veli', models.CharField(max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ozellikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.IntegerField()),
                ('kilo', models.IntegerField()),
                ('tarih', models.DateField(auto_now_add=True)),
                ('sporcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.sporcu')),
            ],
        ),
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=30)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='')),
                ('aktif', models.BooleanField(default=True)),
                ('antrenor', models.ManyToManyField(to='main.antrenor')),
            ],
        ),
        migrations.AddField(
            model_name='sporcu',
            name='takim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.takim'),
        ),
        migrations.CreateModel(
            name='HaftalikAntrenman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarsamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (8, 'Pazar')])),
                ('baslangic', models.TimeField()),
                ('bitis', models.TimeField(null=True)),
                ('yer', models.TextField(choices=[('Hacettepe', 'Hacettepe'), ('Atlas', 'Atlas')], null=True)),
                ('tur', models.TextField(choices=[('Yüzme', 'Yüzme'), ('Kara', 'Kara')], null=True)),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.takim')),
            ],
        ),
        migrations.CreateModel(
            name='Antrenman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.DateField(auto_now_add=True)),
                ('mesafe', models.IntegerField(default=0)),
                ('sporcular', models.ManyToManyField(blank=True, null=True, to='takim.sporcu')),
                ('takimlar', models.ManyToManyField(to='takim.takim')),
            ],
            options={
                'ordering': ['-gun'],
            },
        ),
        migrations.CreateModel(
            name='Yarislar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaris', models.CharField(max_length=100)),
                ('sehir', models.CharField(max_length=100)),
                ('tarih', models.DateField()),
                ('cinsiyet', models.CharField(max_length=100)),
                ('mesafe', models.CharField(max_length=100)),
                ('brans', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=100)),
                ('siralama', models.CharField(max_length=100)),
                ('sporcu', models.CharField(max_length=100)),
                ('yas', models.IntegerField()),
                ('takim', models.CharField(max_length=100)),
                ('zaman', models.TimeField()),
                ('puan', models.CharField(max_length=100)),
                ('sporcu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.sporcu')),
            ],
        ),
    ]
