# Generated by Django 5.1.5 on 2025-03-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='cinsiyet',
            field=models.CharField(default='Erkek', max_length=30),
            preserve_default=False,
        ),
    ]
