# Generated by Django 5.1.7 on 2025-03-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barajlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaris', models.CharField(max_length=100)),
                ('sehir', models.CharField(max_length=100)),
                ('tarih', models.DateField(max_length=100)),
                ('yas', models.IntegerField()),
                ('yas_ust', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarajBrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.CharField(max_length=100)),
                ('mesafe', models.CharField(max_length=100)),
                ('baraj', models.TimeField()),
                ('cinsiyet', models.CharField(max_length=100)),
                ('baraj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.barajlar')),
            ],
        ),
    ]
