# Generated by Django 5.1.7 on 2025-03-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0002_barajlar_barajbrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barajbrans',
            name='baraj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brans_baraj', to='takim.barajlar'),
        ),
        migrations.AlterField(
            model_name='barajbrans',
            name='brans',
            field=models.CharField(choices=[('Serbest', 'Serbest'), ('Kurbağalama', 'Kurbağalama'), ('Kelebek', 'Kelebek'), ('Sırtüstü', 'Sırtüstü'), ('Karışık', 'Karışık')], max_length=100),
        ),
        migrations.AlterField(
            model_name='barajbrans',
            name='cinsiyet',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=100),
        ),
        migrations.AlterField(
            model_name='barajbrans',
            name='mesafe',
            field=models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('400', '400'), ('800', '800'), ('1500', '1500')], max_length=100),
        ),
    ]
