# Generated by Django 5.1.5 on 2025-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0002_alter_sporcu_cinsiyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='cinsiyet',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=30),
        ),
    ]
