# Generated by Django 5.1.5 on 2025-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0003_alter_sporcu_cinsiyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarislar',
            name='tarih',
            field=models.DateField(),
        ),
    ]
