# Generated by Django 5.1.5 on 2025-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0005_alter_yarislar_zaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarislar',
            name='zaman',
            field=models.DurationField(),
        ),
    ]
