# Generated by Django 5.1.5 on 2025-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0006_alter_yarislar_zaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarislar',
            name='zaman1',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='yarislar',
            name='zaman',
            field=models.CharField(max_length=30),
        ),
    ]
