# Generated by Django 5.1.5 on 2025-03-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0007_yarislar_zaman1_alter_yarislar_zaman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarislar',
            name='zaman1',
        ),
        migrations.AlterField(
            model_name='yarislar',
            name='zaman',
            field=models.DurationField(max_length=30),
        ),
    ]
