# Generated by Django 5.1.5 on 2025-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0010_alter_yarislar_zaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barajlar',
            name='baraj',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='yarislar',
            name='zaman',
            field=models.TimeField(),
        ),
    ]
